---
abstract: 'Generate Javascript Objects from you Validation Classes'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class-Plugin-JavascriptObjects
requires:
  JSON: 0
  Validation::Class: 0
resources:
  bugtracker: https://github.com/alnewkirk/Validation-Class-Plugin-JavascriptObjects/issues
  homepage: https://github.com/alnewkirk/Validation-Class-Plugin-JavascriptObjects
  repository: git://github.com/alnewkirk/Validation-Class-Plugin-JavascriptObjects.git
version: 0.01
